#pragma once
#define TILE_SIZE 64
#define TILES_WIDE 1920 / TILE_SIZE / 2
#define TILES_TALL TILES_WIDE
#define WINDOW_WIDTH TILES_WIDE* TILE_SIZE
#define WINDOW_HEIGHT TILES_TALL* TILE_SIZE
#define FRAMES_PER_SECOND 60
#define MS_PER_FRAME ((1.f / 60.f) * 1000.f)
#define MS_PER_UPDATE MS_PER_FRAME * 8.f
#define MAX_APPLES 16
#define MAX_INPUT_QUEUE_SIZE 2
#define MAX_SCORE_TEXT 128
#define MS_PER_APPLE_SPAWN 4 * 1000
#define GROWTH_FACTOR 2
#define MAX_WORM_LENGTH TILES_WIDE* TILES_TALL
#define RESPAWN_TIME 1000